version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_LIST_ASSETSProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_LIST_ASSETSProject
  gitUsername: karthikbm
  gitBranch: main
- name: OriginKMAT_Jun2024
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: ApiClient
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
services:
- serviceName: project.kmat_list_assets.integrations:add_ints
  packages:
  - name: KMAT_LIST_ASSETSProject
    version: "1.0"
  - name: ApiClient
    version: "1.0"
  - name: OriginKMAT_Jun2024
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.968
