version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_LIST_ASSETSProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_LIST_ASSETSProject
  gitUsername: karthikbm
  gitBranch: main
- name: ApiClient
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: WmSalesforceProvider
  gitServerName: KMAT_GHES
  gitUrl: https://github.webmethods.io/AIM
  gitUsername: kmat
  gitTag: v10.7.0
services:
- serviceName: project.kmat_list_assets.integrations:add_ints
  packages:
  - name: KMAT_LIST_ASSETSProject
    version: "1.0"
  - name: ApiClient
    version: "1.0"
  - name: OriginKMAT_Jun2024
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.968
- serviceName: project.kmat_list_assets.integrations:SF_Query_Accounts
  packages:
  - name: KMAT_LIST_ASSETSProject
    version: "1.0"
  - name: ApiClient
    version: "1.0"
  - name: OriginKMAT_Jun2024
    version: "1.0"
- serviceName: SF_CCS:SF_DEV_QueryAccounts
  packages:
  - name: OriginKMAT_Jun2024
    version: "1.0"
